/** Audit action constants for the Auth domain */
export const AUTH_AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILED: "USER_LOGIN_FAILED",
  LOGIN_LOCKED: "USER_LOGIN_ACCOUNT_LOCKED",
  LOGOUT: "USER_LOGOUT",
  TOKEN_REFRESHED: "USER_TOKEN_REFRESHED",
  TOKEN_THEFT_DETECTED: "USER_TOKEN_THEFT_DETECTED",
  PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  PASSWORD_CHANGE_FAILED: "USER_PASSWORD_CHANGE_FAILED",
  PASSWORD_RESET_REQUESTED: "USER_PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "USER_PASSWORD_RESET_COMPLETED",
  PASSWORD_RESET_INVALID_TOKEN: "USER_PASSWORD_RESET_INVALID_TOKEN",
} as const;
