/** Audit action constants for the Charging domain */
export const AUDIT_ACTIONS = {
  SESSION_STARTED: "CHARGING_SESSION_STARTED",
  SESSION_STOPPED: "CHARGING_SESSION_STOPPED",
  SESSION_START_DENIED: "CHARGING_SESSION_START_DENIED",
} as const;
